title: ZBVAE
author: Billy Zhang
description: My personal blog using jekyll theme.

highlighter: rouge
permalink: /:title

baseurl: http://www.loczb.com

# Custom options:
# color_scheme: azul|ruby|amber|avocado
color_scheme: azul
markdown: kramdown
toc_levels: 1..4

